name: module3_task3
on:
  push:
    branches:
      - main
    tags:
      - '1.0.0'
  schedule:
    - cron: '0 0 * * *'
jobs:
  Create-tag-release:
    name: Create tag release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task3/setup.sh
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make package
      - run: cd module3_task3 && make lint
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - name: Zip file
        uses: actions/upload-artifact@v3
        with:
          path: module3_task3/awesome-website.zip
      - name: Tag Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '1.0.0'
          files: |
            module3_task3/DEPLOY.md
            module3_task3/awesome-website.zip
          body_path: module3_task3/DEPLOY.md
