name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  Execute-make-commands:
    name: Execute make commands
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task1/setup.sh
      - run: cd module3_task1 && make build
