name: module4_task1
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]
  push:
    branches:
      - main
    tags:
      - "1.0.1"
  schedule:
    - cron: "0 0 * * *"
jobs:
  Create-tag-release:
    name: Create tag release
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module4_task1/setup.sh
      - run: cd module4_task1 && sudo make build
      - run: cd module4_task1 && sudo make package
      - run: cd module4_task1 && sudo make lint
      - run: cd module4_task1 && make unit-tests
      - run: cd module4_task1 && make integration-tests
      - run: cd module4_task1 && make validate
      - uses: actions/upload-artifact@v3
        with:
          path: module4_task1/awesome-website.zip
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.1')
        with:
          tag_name: "1.0.1"
          files: |
            module4_task1/awesome-website.zip
            module4_task1/DEPLOY.md
          body_path: module4_task1/DEPLOY.md
      - uses: release-drafter/release-drafter@v5
      - uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "module4_task1/dist"
          production-branch: main
          deploy-message: "🚀 Deployed on"
          publish-message: "🎉 Published on"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      - name: Run Docker
        run: cd module4_task1 && make build-docker
