name: release_drafter
on:
  push:
    branches:
      - main
    tags: '1.0.1'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  Create-release-drafter:
    name: Create release drafter
    runs-on: ubuntu-18.04
    permissions: write-all
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "changelog"
          output: changelog.md
